openapi: 3.1.0
info:
  title: Palenca accounts logins API
  description: Palenca API
  version: 2.0.0
tags:
- name: logins
paths:
  /v1/logins/manual-incomplete:
    get:
      tags:
      - logins
      summary: Manual Logins
      operationId: manual_logins_v1_logins_manual_incomplete_get
      parameters:
      - description: Platform code to filter the logins
        required: false
        schema:
          allOf:
          - $ref: '#/components/schemas/PlatformCode'
          description: Platform code to filter the logins
        name: platform
        in: query
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/logins/{login_id}:
    get:
      tags:
      - logins
      summary: Get Login
      operationId: get_login_v1_logins__login_id__get
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Login Id
        name: login_id
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      - required: false
        schema:
          type: string
          title: Accept-Language
        name: accept-language
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/accounts/{account_id}/logins:
    get:
      tags:
      - logins
      summary: Get Logins For Account
      operationId: get_logins_for_account_v1_accounts__account_id__logins_get
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Account Id
        name: account_id
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      - required: false
        schema:
          type: string
          title: Accept-Language
        name: accept-language
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_ListLoginBaseResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/logins/{login_id}/send-webhook:
    post:
      tags:
      - logins
      summary: Send Login Webhook
      operationId: send_login_webhook_v1_logins__login_id__send_webhook_post
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Login Id
        name: login_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_ListLoginBaseResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/logins/search:
    post:
      tags:
      - logins
      summary: List Users
      operationId: list_users_v1_logins_search_post
      parameters:
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchLoginsParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_ListLoginBaseResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ListLoginBaseResponse:
      properties:
        logins:
          items:
            $ref: '#/components/schemas/LoginBaseResponse'
          type: array
          title: Logins
          default: []
      type: object
      title: ListLoginBaseResponse
    LoginStatus:
      enum:
      - created
      - success
      - retry
      - incomplete
      - error
      - pending
      - requires_auth
      - profile_unavailable
      - error_credentials
      - error_otp
      - pending_for_data
      - validation_pending
      - password_validation_pending
      title: LoginStatus
      description: An enumeration.
    SearchLoginsParams:
      properties:
        start_date:
          type: string
          title: Start Date
        end_date:
          type: string
          title: End Date
        options:
          allOf:
          - $ref: '#/components/schemas/PaginationSearchParams'
          title: Options
          default:
            items_per_page: 100
            page: 1
      type: object
      required:
      - start_date
      - end_date
      title: SearchLoginsParams
    ErrorDetailResponse:
      properties:
        message:
          type: string
          title: Message
        location:
          type: string
          title: Location
      type: object
      title: ErrorDetailResponse
    InsightsStatus:
      enum:
      - computed_not_saved
      - incomplete
      - success
      - error
      title: InsightsStatus
      description: An enumeration.
    BaseResponse_ListLoginBaseResponse_:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error:
          $ref: '#/components/schemas/ErrorResponse'
        data:
          $ref: '#/components/schemas/ListLoginBaseResponse'
      type: object
      title: BaseResponse[ListLoginBaseResponse]
      example:
        success: true
        data: {}
        error: {}
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    LoginBaseResponse:
      properties:
        created_at:
          type: string
          format: date-time
          title: Created At
        updated_at:
          type: string
          format: date-time
          title: Updated At
        id:
          type: string
          format: uuid
          title: Id
        bulk_id:
          type: string
          format: uuid
          title: Bulk Id
        status:
          $ref: '#/components/schemas/LoginStatus'
        platform:
          $ref: '#/components/schemas/PlatformCode'
        source:
          $ref: '#/components/schemas/LoginSourceCode'
        status_details:
          $ref: '#/components/schemas/StatusDetails'
        authenticated_at:
          type: string
          format: date-time
          title: Authenticated At
        message:
          type: string
          title: Message
        company_id:
          type: string
          format: uuid
          title: Company Id
        recommendation:
          type: string
          title: Recommendation
        automatic_retry:
          type: boolean
          title: Automatic Retry
        has_insights:
          type: boolean
          title: Has Insights
        insights_status:
          $ref: '#/components/schemas/InsightsStatus'
        insights_status_details:
          $ref: '#/components/schemas/InsightsStatusDetails'
        account_id:
          type: string
          format: uuid
          title: Account Id
      type: object
      title: LoginBaseResponse
    LoginSourceCode:
      enum:
      - widget
      - api
      - legacy
      - refresh
      - connect
      - bulk_upload
      - console
      - platform_retry
      - refresh_earnings
      - refresh_events
      - refresh_profile
      title: LoginSourceCode
      description: An enumeration.
    InsightsStatusDetails:
      enum:
      - empty_employment_events
      - empty_employment_history
      - login_not_success
      - timeout_request
      - lambda_error
      - pending
      title: InsightsStatusDetails
      description: An enumeration.
    StatusDetails:
      enum:
      - bad_request
      - banned
      - invalid_credentials
      - too_many_requests
      - service_unavailable
      - request_timeout
      - access_forbidden
      - platform_error
      - invalid_otp
      - expired_otp
      - invalid_nss
      - invalid_phone
      - invalid_email
      - lambda_error
      - phone_or_code_missing
      - password_missing
      - not_registered
      - login_refused
      - unknown
      - invalid_otp_session
      - invalid_otp_auth_key
      - needs_auth
      - requires_auth
      - curp_not_found
      - could_not_send_otp
      - profile_unavailable
      - no_employment_records
      - account_setup_incomplete
      - identity_verification_failed
      - gov_id_not_in_data_source
      - gov_id_has_inconsistencies
      - mfa_deactivation_required
      - access_token_not_generated
      - two_factor_auth_required
      - captcha_bypass_error
      - invalid_identifier
      - account_blocked
      - proxy_error
      - invalid_captcha
      - invalid_gov_id
      - device_authorization_required
      - max_retries_exceeded
      - task_create_fail
      - invalid_cpf
      - invalid_in_auth_session_id
      - unable_to_get_uber_metrics
      - email_otp_validation_pending
      - login_not_available
      - invalid_password
      - unknown_login_type
      - email_not_validated
      - already_connected
      - missing_social_security_number
      - social_security_number_mismatch
      - zero_quoted_weeks
      - proxy_max_retries_exceeded
      - curp_not_found_in_renapo
      - nss_not_found_in_imss
      - renapo_unavailable
      - service_degradation
      - server_error
      - db_constraint_violation
      - api_forbidden
      - auth_token_expired
      - network_max_retries_exceeded
      - api_service_unavailable_02
      - api_service_unavailable_08
      - lambda_timeout
      - api_service_unavailable
      - auth_max_attempts_exceeded
      - browser_navigation_timeout
      - render_invalid_html
      - browser_connection_timeout
      - parser_invalid_pdf
      - aws_s3_upload_fail
      - network_connectivity_issues
      - auth_invalid_token
      - server_not_found
      - api_server_error
      - network_ssl_error
      - auth_forbidden
      - api_bad_gateway
      - api_server_timeout
      - system_platform_error
      - api_rate_limit_exceeded
      - api_renapo_unavailable
      - user_gov_id_has_inconsistencies
      - user_ssn_missing
      - user_curp_not_found_in_renapo
      - rpci_timeout
      - pending_data_extraction
      - employment_info_in_imss
      - pending_for_data
      - validation_pending
      - password_validation_pending
      - validation_time_expired
      - curp_has_inconsistencies
      - curp_not_in_platform
      - platform_unavailable
      - failed_refresh
      - invalid_schema_response
      - not_available_in_platform
      - user_curp_not_in_platform
      - user_gov_id_not_in_data_source
      - account_not_found
      - profile_not_found
      - unable_to_get_rappi_metrics
      - captcha_required
      - captcha_detected
      - didi_rate_limited
      - device_risk
      - cell_rate_limited
      - resend_limit
      - didi_rejected
      - incomplete_profile
      title: StatusDetails
      description: An enumeration.
    ErrorResponse:
      properties:
        code:
          type: string
          title: Code
        message:
          type: string
          title: Message
        errors:
          items:
            $ref: '#/components/schemas/ErrorDetailResponse'
          type: array
          title: Errors
      type: object
      title: ErrorResponse
    PaginationSearchParams:
      properties:
        items_per_page:
          type: integer
          title: Items Per Page
          default: 100
        page:
          type: integer
          title: Page
          default: 1
      type: object
      title: PaginationSearchParams
    PlatformCode:
      enum:
      - uber
      - didi
      - imss
      - rappi
      - osmos
      - pemex
      - picap
      - ifood
      - issste
      - cabify
      - workday
      - indriver
      - uber_eats
      - didi_food
      - pedidos_ya
      - noventa_nove
      - mensajeros_urbanos
      - rapiboy
      - nueve_nueve_minutos
      - carteira_trabalho
      - mercado_pago
      - nom_gob_cdmx
      - nom_salud_cdmx
      - nom_sep_cdmx
      - nom_sep_qro
      - nom_gob_hidalgo
      - nom_sep_durango
      - nom_ayto_cancun
      - nom_sep_qroo
      - nom_gob_qroo
      - nom_salud_qroo
      - nom_sep_campeche
      - nom_gob_oaxaca
      - nom_sep_oaxaca
      - nom_pensiones_jal
      - nom_gob_nl
      - nom_gob_tamps
      - nom_salud_tamps
      - nom_fiscalia_tamps
      - nom_gob_sonora
      - nom_sep_sonora
      - nom_salud_sonora
      - nom_sep_bcsur
      - nom_gob_edomex
      - nom_sep_edomex
      - nom_gob_tabasco
      - nom_salud_sonora2
      - nom_com_soc_qroo
      - nom_pemex
      - mc_price_shoes
      - mc_avon
      - mc_mary_kay
      - mc_betterware
      - nominativa
      - microempreendedor_individual
      - runa
      - grupo_tress
      - beat
      - clip
      - worky
      - cornershop
      title: PlatformCode
      description: An enumeration.
    BaseResponse:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error:
          $ref: '#/components/schemas/ErrorResponse'
        data:
          title: Data
      type: object
      title: BaseResponse
      example:
        success: true
        data: {}
        error: {}
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
