openapi: 3.1.0
info:
  title: Palenca accounts internal/bulks API
  description: Palenca API
  version: 2.0.0
tags:
- name: internal/bulks
paths:
  /v1/internal/bulks/{bulk_id}/employment-files:
    get:
      tags:
      - internal/bulks
      summary: List Employment Files By Bulk Id
      operationId: list_employment_files_by_bulk_id_v1_internal_bulks__bulk_id__employment_files_get
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Bulk Id
        name: bulk_id
        in: path
      - required: false
        schema:
          type: integer
          title: Page
          default: 1
        name: page
        in: query
      - required: false
        schema:
          type: integer
          title: Items Per Page
          default: 100
        name: items_per_page
        in: query
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasePaginationResponse_EmploymentsFilesBaseResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/internal/bulks/{bulk_id}/identifier/{identifier}:
    delete:
      tags:
      - internal/bulks
      summary: Delete Bulk Account By Identifier
      operationId: delete_bulk_account_by_identifier_v1_internal_bulks__bulk_id__identifier__identifier__delete
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Bulk Id
        name: bulk_id
        in: path
      - required: true
        schema:
          type: string
          title: Identifier
        name: identifier
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_AccountBaseResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    LoginStatus:
      enum:
      - created
      - success
      - retry
      - incomplete
      - error
      - pending
      - requires_auth
      - profile_unavailable
      - error_credentials
      - error_otp
      - pending_for_data
      - validation_pending
      - password_validation_pending
      title: LoginStatus
      description: An enumeration.
    AccountBaseResponse:
      properties:
        account_id:
          type: string
          format: uuid
          title: Account Id
        country:
          $ref: '#/components/schemas/CountryCode'
        platform:
          $ref: '#/components/schemas/PlatformCode'
        identifier:
          type: string
          title: Identifier
        worker_id:
          type: string
          title: Worker Id
        gov_id:
          type: string
          title: Gov Id
        last_successful_connection:
          type: string
          format: date-time
          title: Last Successful Connection
        warning:
          $ref: '#/components/schemas/AccountWarning'
        status:
          $ref: '#/components/schemas/LoginStatus'
        status_details:
          $ref: '#/components/schemas/StatusDetails'
        message:
          type: string
          title: Message
        recommendation:
          type: string
          title: Recommendation
        next_step:
          $ref: '#/components/schemas/LoginTypes'
        created_at:
          type: string
          format: date-time
          title: Created At
      type: object
      required:
      - account_id
      title: AccountBaseResponse
    AccountWarning:
      enum:
      - banned
      - not_registered
      - profile_unavailable
      - needs_auth
      - no_employment_records
      - missing_social_security_number
      - social_security_number_mismatch
      - curp_has_inconsistencies
      - curp_not_in_platform
      - zero_quoted_weeks
      - rpci_backup_process
      - web_scraping_backup_process
      - rider_account
      - fleet_account
      - onboarding
      - didi_auth_app
      - didi_auth_web
      - invalid_captcha
      - incomplete_profile_data
      - id_mismatch
      title: AccountWarning
      description: An enumeration.
    ErrorDetailResponse:
      properties:
        message:
          type: string
          title: Message
        location:
          type: string
          title: Location
      type: object
      title: ErrorDetailResponse
    EmploymentsFilesBaseResponse:
      properties:
        url:
          type: string
          title: Url
        file_type:
          $ref: '#/components/schemas/EmploymentFilesType'
        account_id:
          type: string
          format: uuid
          title: Account Id
      type: object
      title: EmploymentsFilesBaseResponse
    EmploymentFilesType:
      enum:
      - imss_employment_record
      - imss_rpci_pdf
      - buro_insights_employment_record
      - issste_employment_file
      - end_of_rights_pdf
      title: EmploymentFilesType
      description: An enumeration.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    PaginationBaseResponse:
      properties:
        page:
          type: integer
          title: Page
        items_per_page:
          type: integer
          title: Items Per Page
        total_items:
          type: integer
          title: Total Items
        total_pages:
          type: integer
          title: Total Pages
      type: object
      title: PaginationBaseResponse
    BasePaginationResponse_EmploymentsFilesBaseResponse_:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error:
          $ref: '#/components/schemas/ErrorResponse'
        data:
          $ref: '#/components/schemas/EmploymentsFilesBaseResponse'
        pagination:
          $ref: '#/components/schemas/PaginationBaseResponse'
      type: object
      title: BasePaginationResponse[EmploymentsFilesBaseResponse]
      example:
        success: true
        data: {}
        error: {}
        pagination: {}
    BaseResponse_AccountBaseResponse_:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error:
          $ref: '#/components/schemas/ErrorResponse'
        data:
          $ref: '#/components/schemas/AccountBaseResponse'
      type: object
      title: BaseResponse[AccountBaseResponse]
      example:
        success: true
        data: {}
        error: {}
    CountryCode:
      enum:
      - mx
      - co
      - br
      - ar
      - cl
      - pe
      - us
      - cr
      - pa
      - ec
      - bo
      - ve
      - sv
      - do
      title: CountryCode
      description: An enumeration.
    ErrorResponse:
      properties:
        code:
          type: string
          title: Code
        message:
          type: string
          title: Message
        errors:
          items:
            $ref: '#/components/schemas/ErrorDetailResponse'
          type: array
          title: Errors
      type: object
      title: ErrorResponse
    PlatformCode:
      enum:
      - uber
      - didi
      - imss
      - rappi
      - osmos
      - pemex
      - picap
      - ifood
      - issste
      - cabify
      - workday
      - indriver
      - uber_eats
      - didi_food
      - pedidos_ya
      - noventa_nove
      - mensajeros_urbanos
      - rapiboy
      - nueve_nueve_minutos
      - carteira_trabalho
      - mercado_pago
      - nom_gob_cdmx
      - nom_salud_cdmx
      - nom_sep_cdmx
      - nom_sep_qro
      - nom_gob_hidalgo
      - nom_sep_durango
      - nom_ayto_cancun
      - nom_sep_qroo
      - nom_gob_qroo
      - nom_salud_qroo
      - nom_sep_campeche
      - nom_gob_oaxaca
      - nom_sep_oaxaca
      - nom_pensiones_jal
      - nom_gob_nl
      - nom_gob_tamps
      - nom_salud_tamps
      - nom_fiscalia_tamps
      - nom_gob_sonora
      - nom_sep_sonora
      - nom_salud_sonora
      - nom_sep_bcsur
      - nom_gob_edomex
      - nom_sep_edomex
      - nom_gob_tabasco
      - nom_salud_sonora2
      - nom_com_soc_qroo
      - nom_pemex
      - mc_price_shoes
      - mc_avon
      - mc_mary_kay
      - mc_betterware
      - nominativa
      - microempreendedor_individual
      - runa
      - grupo_tress
      - beat
      - clip
      - worky
      - cornershop
      title: PlatformCode
      description: An enumeration.
    StatusDetails:
      enum:
      - bad_request
      - banned
      - invalid_credentials
      - too_many_requests
      - service_unavailable
      - request_timeout
      - access_forbidden
      - platform_error
      - invalid_otp
      - expired_otp
      - invalid_nss
      - invalid_phone
      - invalid_email
      - lambda_error
      - phone_or_code_missing
      - password_missing
      - not_registered
      - login_refused
      - unknown
      - invalid_otp_session
      - invalid_otp_auth_key
      - needs_auth
      - requires_auth
      - curp_not_found
      - could_not_send_otp
      - profile_unavailable
      - no_employment_records
      - account_setup_incomplete
      - identity_verification_failed
      - gov_id_not_in_data_source
      - gov_id_has_inconsistencies
      - mfa_deactivation_required
      - access_token_not_generated
      - two_factor_auth_required
      - captcha_bypass_error
      - invalid_identifier
      - account_blocked
      - proxy_error
      - invalid_captcha
      - invalid_gov_id
      - device_authorization_required
      - max_retries_exceeded
      - task_create_fail
      - invalid_cpf
      - invalid_in_auth_session_id
      - unable_to_get_uber_metrics
      - email_otp_validation_pending
      - login_not_available
      - invalid_password
      - unknown_login_type
      - email_not_validated
      - already_connected
      - missing_social_security_number
      - social_security_number_mismatch
      - zero_quoted_weeks
      - proxy_max_retries_exceeded
      - curp_not_found_in_renapo
      - nss_not_found_in_imss
      - renapo_unavailable
      - service_degradation
      - server_error
      - db_constraint_violation
      - api_forbidden
      - auth_token_expired
      - network_max_retries_exceeded
      - api_service_unavailable_02
      - api_service_unavailable_08
      - lambda_timeout
      - api_service_unavailable
      - auth_max_attempts_exceeded
      - browser_navigation_timeout
      - render_invalid_html
      - browser_connection_timeout
      - parser_invalid_pdf
      - aws_s3_upload_fail
      - network_connectivity_issues
      - auth_invalid_token
      - server_not_found
      - api_server_error
      - network_ssl_error
      - auth_forbidden
      - api_bad_gateway
      - api_server_timeout
      - system_platform_error
      - api_rate_limit_exceeded
      - api_renapo_unavailable
      - user_gov_id_has_inconsistencies
      - user_ssn_missing
      - user_curp_not_found_in_renapo
      - rpci_timeout
      - pending_data_extraction
      - employment_info_in_imss
      - pending_for_data
      - validation_pending
      - password_validation_pending
      - validation_time_expired
      - curp_has_inconsistencies
      - curp_not_in_platform
      - platform_unavailable
      - failed_refresh
      - invalid_schema_response
      - not_available_in_platform
      - user_curp_not_in_platform
      - user_gov_id_not_in_data_source
      - account_not_found
      - profile_not_found
      - unable_to_get_rappi_metrics
      - captcha_required
      - captcha_detected
      - didi_rate_limited
      - device_risk
      - cell_rate_limited
      - resend_limit
      - didi_rejected
      - incomplete_profile
      title: StatusDetails
      description: An enumeration.
    LoginTypes:
      enum:
      - curp
      - otp
      - totp
      - pilot
      - email_otp
      - credentials
      - phone_voice_otp
      - phone_whatsapp_otp
      title: LoginTypes
      description: An enumeration.
