openapi: 3.1.0
info:
  title: Palenca accounts insights API
  description: Palenca API
  version: 2.0.0
tags:
- name: insights
paths:
  /v1/insights/reports/{account_id}:
    post:
      tags:
      - insights
      summary: Send Report Content
      operationId: send_report_content_v1_insights_reports__account_id__post
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Account Id
        name: account_id
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/insights/{account_id}/extended:
    get:
      tags:
      - insights
      summary: Compute Buro Insights
      operationId: compute_buro_insights_v1_insights__account_id__extended_get
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Account Id
        name: account_id
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/insights/{account_id}/extended/pdf:
    get:
      tags:
      - insights
      summary: Compute Buro Insights For Pdf
      operationId: compute_buro_insights_for_pdf_v1_insights__account_id__extended_pdf_get
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Account Id
        name: account_id
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /console/insights/graphs/benchmarks:
    post:
      tags:
      - insights
      summary: Send Platform Benchmarks
      operationId: send_platform_benchmarks_console_insights_graphs_benchmarks_post
      parameters:
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlatformBenchmarksParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /console/insights/graphs/employment/salary-progression:
    post:
      tags:
      - insights
      summary: Get Account Salary Progression Over Time
      operationId: get_account_salary_progression_over_time_console_insights_graphs_employment_salary_progression_post
      parameters:
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndividualAccountInsightsParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /console/insights/graphs/gig/earning-detail:
    post:
      tags:
      - insights
      summary: Get Account Earning Detail
      operationId: get_account_earning_detail_console_insights_graphs_gig_earning_detail_post
      parameters:
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndividualAccountInsightsParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /console/insights/extended:
    post:
      tags:
      - insights
      summary: Compute Extended Insights
      operationId: compute_extended_insights_console_insights_extended_post
      parameters:
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComputeExtendedInsightsParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    PlatformBenchmarksParams:
      properties:
        platform:
          $ref: '#/components/schemas/PlatformCode'
        country:
          $ref: '#/components/schemas/CountryCode'
      type: object
      required:
      - platform
      - country
      title: PlatformBenchmarksParams
    ComputeExtendedInsightsParams:
      properties:
        account_id:
          type: string
          format: uuid
          title: Account Id
        company_id:
          type: string
          format: uuid
          title: Company Id
      type: object
      required:
      - account_id
      - company_id
      title: ComputeExtendedInsightsParams
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    IndividualAccountInsightsParams:
      properties:
        account_id:
          type: string
          format: uuid
          title: Account Id
      type: object
      required:
      - account_id
      title: IndividualAccountInsightsParams
    CountryCode:
      enum:
      - mx
      - co
      - br
      - ar
      - cl
      - pe
      - us
      - cr
      - pa
      - ec
      - bo
      - ve
      - sv
      - do
      title: CountryCode
      description: An enumeration.
    PlatformCode:
      enum:
      - uber
      - didi
      - imss
      - rappi
      - osmos
      - pemex
      - picap
      - ifood
      - issste
      - cabify
      - workday
      - indriver
      - uber_eats
      - didi_food
      - pedidos_ya
      - noventa_nove
      - mensajeros_urbanos
      - rapiboy
      - nueve_nueve_minutos
      - carteira_trabalho
      - mercado_pago
      - nom_gob_cdmx
      - nom_salud_cdmx
      - nom_sep_cdmx
      - nom_sep_qro
      - nom_gob_hidalgo
      - nom_sep_durango
      - nom_ayto_cancun
      - nom_sep_qroo
      - nom_gob_qroo
      - nom_salud_qroo
      - nom_sep_campeche
      - nom_gob_oaxaca
      - nom_sep_oaxaca
      - nom_pensiones_jal
      - nom_gob_nl
      - nom_gob_tamps
      - nom_salud_tamps
      - nom_fiscalia_tamps
      - nom_gob_sonora
      - nom_sep_sonora
      - nom_salud_sonora
      - nom_sep_bcsur
      - nom_gob_edomex
      - nom_sep_edomex
      - nom_gob_tabasco
      - nom_salud_sonora2
      - nom_com_soc_qroo
      - nom_pemex
      - mc_price_shoes
      - mc_avon
      - mc_mary_kay
      - mc_betterware
      - nominativa
      - microempreendedor_individual
      - runa
      - grupo_tress
      - beat
      - clip
      - worky
      - cornershop
      title: PlatformCode
      description: An enumeration.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
