openapi: 3.1.0
info:
  title: Palenca accounts console/status API
  description: Palenca API
  version: 2.0.0
tags:
- name: console/status
paths:
  /console/status/{status_details}:
    get:
      tags:
      - console/status
      summary: Get Status
      operationId: get_status_console_status__status_details__get
      parameters:
      - required: true
        schema:
          $ref: '#/components/schemas/StatusDetails'
        name: status_details
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_StatusResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    BaseResponse_StatusResponse_:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error:
          $ref: '#/components/schemas/ErrorResponse'
        data:
          $ref: '#/components/schemas/StatusResponse'
      type: object
      title: BaseResponse[StatusResponse]
      example:
        success: true
        data: {}
        error: {}
    ErrorDetailResponse:
      properties:
        message:
          type: string
          title: Message
        location:
          type: string
          title: Location
      type: object
      title: ErrorDetailResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    StatusResponse:
      properties:
        status_details:
          type: string
          title: Status Details
        status:
          type: string
          title: Status
        code:
          type: string
          title: Code
        message:
          $ref: '#/components/schemas/TranslationsResponse'
        recommendation:
          $ref: '#/components/schemas/TranslationsResponse'
      type: object
      required:
      - message
      - recommendation
      title: StatusResponse
    ErrorResponse:
      properties:
        code:
          type: string
          title: Code
        message:
          type: string
          title: Message
        errors:
          items:
            $ref: '#/components/schemas/ErrorDetailResponse'
          type: array
          title: Errors
      type: object
      title: ErrorResponse
    TranslationsResponse:
      properties:
        en:
          type: string
          title: En
        es:
          type: string
          title: Es
        pt:
          type: string
          title: Pt
      type: object
      title: TranslationsResponse
    StatusDetails:
      enum:
      - bad_request
      - banned
      - invalid_credentials
      - too_many_requests
      - service_unavailable
      - request_timeout
      - access_forbidden
      - platform_error
      - invalid_otp
      - expired_otp
      - invalid_nss
      - invalid_phone
      - invalid_email
      - lambda_error
      - phone_or_code_missing
      - password_missing
      - not_registered
      - login_refused
      - unknown
      - invalid_otp_session
      - invalid_otp_auth_key
      - needs_auth
      - requires_auth
      - curp_not_found
      - could_not_send_otp
      - profile_unavailable
      - no_employment_records
      - account_setup_incomplete
      - identity_verification_failed
      - gov_id_not_in_data_source
      - gov_id_has_inconsistencies
      - mfa_deactivation_required
      - access_token_not_generated
      - two_factor_auth_required
      - captcha_bypass_error
      - invalid_identifier
      - account_blocked
      - proxy_error
      - invalid_captcha
      - invalid_gov_id
      - device_authorization_required
      - max_retries_exceeded
      - task_create_fail
      - invalid_cpf
      - invalid_in_auth_session_id
      - unable_to_get_uber_metrics
      - email_otp_validation_pending
      - login_not_available
      - invalid_password
      - unknown_login_type
      - email_not_validated
      - already_connected
      - missing_social_security_number
      - social_security_number_mismatch
      - zero_quoted_weeks
      - proxy_max_retries_exceeded
      - curp_not_found_in_renapo
      - nss_not_found_in_imss
      - renapo_unavailable
      - service_degradation
      - server_error
      - db_constraint_violation
      - api_forbidden
      - auth_token_expired
      - network_max_retries_exceeded
      - api_service_unavailable_02
      - api_service_unavailable_08
      - lambda_timeout
      - api_service_unavailable
      - auth_max_attempts_exceeded
      - browser_navigation_timeout
      - render_invalid_html
      - browser_connection_timeout
      - parser_invalid_pdf
      - aws_s3_upload_fail
      - network_connectivity_issues
      - auth_invalid_token
      - server_not_found
      - api_server_error
      - network_ssl_error
      - auth_forbidden
      - api_bad_gateway
      - api_server_timeout
      - system_platform_error
      - api_rate_limit_exceeded
      - api_renapo_unavailable
      - user_gov_id_has_inconsistencies
      - user_ssn_missing
      - user_curp_not_found_in_renapo
      - rpci_timeout
      - pending_data_extraction
      - employment_info_in_imss
      - pending_for_data
      - validation_pending
      - password_validation_pending
      - validation_time_expired
      - curp_has_inconsistencies
      - curp_not_in_platform
      - platform_unavailable
      - failed_refresh
      - invalid_schema_response
      - not_available_in_platform
      - user_curp_not_in_platform
      - user_gov_id_not_in_data_source
      - account_not_found
      - profile_not_found
      - unable_to_get_rappi_metrics
      - captcha_required
      - captcha_detected
      - didi_rate_limited
      - device_risk
      - cell_rate_limited
      - resend_limit
      - didi_rejected
      - incomplete_profile
      title: StatusDetails
      description: An enumeration.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
